### ISSUE TITLE
swaggerize-builder does not work with enjoi 0.2.1

### ISSUE THREAD

**Issue by Adrien-Martins** [krakenjs/swaggerize-builder#35]
Swaggerize-builder does not work with the new version of enjoi (0.2.1).
Tests no longer pass with this version.

**Comment by tlivings** [comment]
Fixed with `enjoi@0.2.2`. 

Sorry, enjoi tests didn't capture this edge.

**Comment by Adrien-Martins** [comment]
All works again now.
Thanks !
